git submodule add https://github.com/moll/vim-node.git dotfiles/vim/bundle/vim-node 
git submodule add https://github.com/vim-scripts/pep8.git dotfiles/vim/bundle/pep8
git submodule add https://github.com/Rykka/riv.vim.git dotfiles/vim/bundle/riv.vim
git submodule add git://github.com/godlygeek/tabular.git dotfiles/vim/bundle/tabular
git submodule add https://github.com/tomtom/tcomment_vim.git dotfiles/vim/bundle/tcomment_vim
git submodule add https://github.com/tomtom/tcomment_vim.git dotfiles/vim/bundle/tcomment_vim
git submodule add git://github.com/Lokaltog/vim-easymotion.git dotfiles/vim/bundle/vim-easymotion
git submodule add https://github.com/nvie/vim-flake8.git dotfiles/vim/bundle/vim-flake8
git submodule add git://github.com/tpope/vim-surround.git dotfiles/vim/bundle/vim-surround
git submodule add https://github.com/scrooloose/syntastic.git dotfiles/vim/bundle/syntastic
git submodule add https://github.com/davidhalter/jedi-vim.git dotfiles/vim/bundle/jedi-vim
git submodule add https://github.com/flazz/vim-colorschemes.git dotfiles/vim/bundle/colorschemes
git submodule add https://github.com/moretension/duti.git utils/duti
